export const environment = {
  SERVICEROLEKEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJxbnd4emRxZmttdWp6cWdreXZxIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTcyMTA1MDIwMiwiZXhwIjoyMDM2NjI2MjAyfQ.nt_CHK0ISYb1D9zlgfax7CIoSM87ccgoBB_Se3zrw38"

  };
